version: "3.8"

services:
  web:
    build: .
    container_name: flask_hit_counter
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # So SQLite file and source code persist
    environment:
      - FLASK_ENV=development
    command: python app.py
